### ISSUE TITLE
Uninitialized constant Page while running bin/rake db:setup

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora-project-site#92]
```
-- create_table("assets", {:force=>true})
   -> 0.0643s
-- create_table("blogposts", {:force=>true})
   -> 0.0547s
-- create_table("planet_entries", {:force=>true})
   -> 0.0555s
-- create_table("planet_feeds", {:force=>true})
   -> 0.0567s
-- create_table("rails_admin_histories", {:force=>true})
   -> 0.0571s
-- add_index("rails_admin_histories", ["item", "table", "month", "year"], {:name=>"index_rails_admin_histories", :using=>:btree})
   -> 0.0539s
-- create_table("users", {:force=>true})
   -> 0.0618s
-- add_index("users", ["email"], {:name=>"index_users_on_email", :unique=>true, :using=>:btree})
   -> 0.0434s
-- add_index("users", ["reset_password_token"], {:name=>"index_users_on_reset_password_token", :unique=>true, :using=>:btree})
   -> 0.0467s
-- initialize_schema_migrations_table()
   -> 0.1538s
-- create_table("assets", {:force=>true})
   -> 0.0549s
-- create_table("blogposts", {:force=>true})
   -> 0.0640s
-- create_table("planet_entries", {:force=>true})
   -> 0.0601s
-- create_table("planet_feeds", {:force=>true})
   -> 0.0588s
-- create_table("rails_admin_histories", {:force=>true})
   -> 0.0600s
-- add_index("rails_admin_histories", ["item", "table", "month", "year"], {:name=>"index_rails_admin_histories", :using=>:btree})
   -> 0.0483s
-- create_table("users", {:force=>true})
   -> 0.0701s
-- add_index("users", ["email"], {:name=>"index_users_on_email", :unique=>true, :using=>:btree})
   -> 0.0483s
-- add_index("users", ["reset_password_token"], {:name=>"index_users_on_reset_password_token", :unique=>true, :using=>:btree})
   -> 0.0434s
-- initialize_schema_migrations_table()
   -> 0.1595s
rake aborted!
NameError: uninitialized constant Page
/home/steffen/projects/diaspora-project-site/db/seeds.rb:9:in `<top (required)>'
/home/steffen/.gem/ruby/2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:547:in `load_seed'
/home/steffen/.gem/ruby/2.3.3/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:251:in `load_seed'
/home/steffen/.gem/ruby/2.3.3/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
```

I'm not sure what that line should do and if we can just drop it.

**Comment by denschub** [comment]
Yeah, looks weird. 🗑 it.
